### ISSUE TITLE
Bottom Navigation 

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#10]
After login-singup page, implement a common bottom Navigation bar.
The required icons are present in the respective asset folder, import them before you use it.
Please refer to this [design](https://xd.adobe.com/view/8ac5be57-dfd4-47f0-a4e9-4ec8285b55cc-df96/screen/88dcfa49-f896-4483-bdc6-373598968c11/)
![bottom navbar](https://user-images.githubusercontent.com/55777560/105080424-d04a2580-5ab6-11eb-9f7b-874acde921ce.PNG)
When you create a PR, please also add a screenshot to it.

**Comment by niloysikdar** [comment]
Hello @samflab mam , want to work on this issue , assign me please .
-- Niloy Sikdar, JWOC mentee .

**Comment by samflab** [comment]
assigned you this issue
