### ISSUE TITLE
User Details Page

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#15]
This page will display the basic user details like name, email, phone, etc. This page should appear when you click the hamburger menu button in the AppBar.
Follow this [design](https://xd.adobe.com/view/8ac5be57-dfd4-47f0-a4e9-4ec8285b55cc-df96/screen/fb55629a-67f1-4188-b576-c141bbb86aa8/)
- use dummy values, later on it will implemented with backend.
- implement the navigation and page transition
- add a logout button, its not included in the design.
- add the screenshot of the page when you make a PR

**Comment by shagun25** [comment]
would like to contribute on this.
@samflab

**Comment by samflab** [comment]
assigned you this issue.

**Comment by samflab** [comment]
@shagun25 are you still working on this issue? what's the update?

**Comment by shagun25** [comment]
Yes working.

**Comment by samflab** [comment]
@shagun you have surpassed the time limit. Please make a PR soon otherwise I will remove you from this issue.

**Comment by samflab** [comment]
removing you from this issue.

**Comment by niloysikdar** [comment]
Want to fix this one.

**Comment by samflab** [comment]
@Niloy-Sikdar-001 assigned.
