### ISSUE TITLE
User Details Page- Extended

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#16]
Follow this [design](https://xd.adobe.com/view/8ac5be57-dfd4-47f0-a4e9-4ec8285b55cc-df96/screen/156243f1-ea49-4ea4-91f6-b9675ca8525a/) and [this](https://xd.adobe.com/view/8ac5be57-dfd4-47f0-a4e9-4ec8285b55cc-df96/screen/5e281bec-01af-4c6f-a880-18cd448ce8b1/)
- The section under 'Account"  and 'Support' appear when you click on it.
- In this page, users can update their details.
- The fields will become editable only when the user clicks the edit button, otherwise it will display the user details. 
- Add a Save Button beside the Edit Button, or you can toggle between the both. Do however you like it.

**Comment by shagun25** [comment]
would like to take this issue up.
can you assign me.
@samflab

**Comment by samflab** [comment]
assigned it to you.

**Comment by samflab** [comment]
removing you from this issue.

**Comment by niloysikdar** [comment]
Want to fix this one .

**Comment by samflab** [comment]
assigned!
