### ISSUE TITLE
Sign up Page

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#2]
Add the frontend for the Sign up Page.
Please follow this [design](https://xd.adobe.com/view/8ac5be57-dfd4-47f0-a4e9-4ec8285b55cc-df96/screen/03a4f412-435e-4ef4-a606-75d0ad292120/) for the page
When you create a PR, please also add a screenshot to it.

**Comment by Ankitpd** [comment]
I want to solve this issue.

**Comment by samflab** [comment]
assigned you this issue. please follow the design as specified.
You have a day to submit your PR. If you are unable to make your PR then I will have to un-assign you from this issue

**Comment by samflab** [comment]
@Ankitpd  are you done with it? Its an easy issue so you only have a day to finish it.

**Comment by samflab** [comment]
@Ankitpd I am removing you from this issue as you have surpassed the time limit for this easy issue, which is one day.

**Comment by niloysikdar** [comment]
Want to fix this . -- JWOC mentee

**Comment by samflab** [comment]
assigned you this issue @Niloy-Sikdar-001
