### ISSUE TITLE
Workout Page-Buttons

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#20]
Make the set of horizontal scroll buttons.
Refer to the [design](https://xd.adobe.com/view/8ac5be57-dfd4-47f0-a4e9-4ec8285b55cc-df96/screen/35d1f7f2-cd60-43e6-9825-29f1d0605309/)
![Capture](https://user-images.githubusercontent.com/55777560/105624237-31bb1d00-5e46-11eb-9610-35124936f064.PNG)
![1](https://user-images.githubusercontent.com/55777560/105624239-4a2b3780-5e46-11eb-9982-976a512fbb91.PNG)

**Comment by niloysikdar** [comment]
Want to work on this issue . Please assign me if possible .

**Comment by samflab** [comment]
assigned it to you.
