### ISSUE TITLE
Dance Page

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#22]
Add the cards to this [page](https://xd.adobe.com/view/8ac5be57-dfd4-47f0-a4e9-4ec8285b55cc-df96/screen/0346c97f-4d23-47c7-aa24-7d9d3a980d9f/) Again, we will be integrating it with the backend so work accordingly.

**Comment by niloysikdar** [comment]
Want to fix this .

**Comment by samflab** [comment]
assigned.
