### ISSUE TITLE
Diet Page-Veg

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#23]
Follow this [design](https://xd.adobe.com/view/8ac5be57-dfd4-47f0-a4e9-4ec8285b55cc-df96/screen/8b80b38f-42bb-40c5-acd2-679e9da705ac/)
- Add the screenshots while making a PR.

**Comment by niloysikdar** [comment]
Want to work on this .

**Comment by samflab** [comment]
assigned it to you.
