### ISSUE TITLE
Message Box

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#26]
Add the message [box](https://xd.adobe.com/view/8ac5be57-dfd4-47f0-a4e9-4ec8285b55cc-df96/screen/7cfcf13f-beea-4d95-80ec-bae23bb50320/) wherever necessary. 
- when users login, display a message 'Welcome to Fitility'
- when a login fails display a message 'Login failed. try again later'
- when a new user signs up, 'Welcome to fitility. Login to confirm'
- when a sign in fails display appropriate msgs like email already in use or password too small.

**Comment by shibam-naskar** [comment]
i want todo this

**Comment by samflab** [comment]
assigned it to you. Since its an easy issue, you have one day to make a PR.

**Comment by samflab** [comment]
@shibam-naskar are you working on this issue? You have surpassed the duration of an easy issue.

**Comment by samflab** [comment]
its been 3 days the issue was assigned to you. You haven't given me any updates, so I am removing you from this issue.

**Comment by niloysikdar** [comment]
Want to work on this.

**Comment by samflab** [comment]
assigned
