### ISSUE TITLE
Reset Password Page

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#3]
Please follow this [design](https://xd.adobe.com/view/8ac5be57-dfd4-47f0-a4e9-4ec8285b55cc-df96/screen/57d42ae5-1f72-4979-a51a-0404c2b950cd/)
- Please exclude the last 2 textbox and replace the verify email button with reset password
- When you create a PR, please also add a screenshot to it.

**Comment by Ankitpd** [comment]
I want to solve this issue.

**Comment by shagun25** [comment]
I would like to contribute, can I take this issue.
@samflab

**Comment by samflab** [comment]
@shagun25 assigned you this issue as Ankit was unable to finish the previously assigned issue. Remember as its an easy issue, you have 1 day to finish it.

**Comment by niloysikdar** [comment]
I would like to work on this issue .

**Comment by shagun25** [comment]
> @shagun25 assigned you this issue as Ankit was unable to finish the previously assigned issue. Remember as its an easy issue, you have 1 day to finish it.

Working on this issue , due to my exams I am quite late in PR , but will do it by today.

**Comment by samflab** [comment]
@shagun25 glad that you informed. take your time :)

**Comment by samflab** [comment]
> I would like to work on this issue .

I can't assign you to this issue, since Shagun is already assigned to this issue.
