### ISSUE TITLE
Admin Panel : Add the Login Page

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#35]
Since we are designing the Admin panel so no Sign up Page will be required. 
Make the necessary changes in this [folder](https://github.com/samflab/Fitility-OpenSource/tree/master/fitility_admin)
Refer to this [design](https://www.figma.com/proto/cEXaOK7jOuq1neyWXJAN5g/Untitled?node-id=7%3A221&scaling=scale-down)
If the link is not working, you may refer to this image:
![admin login](https://user-images.githubusercontent.com/55777560/106121179-474d8100-617d-11eb-976a-e98736b631e7.PNG)

**Comment by niloysikdar** [comment]
Want to fix.

**Comment by samflab** [comment]
assigned
