### ISSUE TITLE
Admin Panel : Home Page (Adding Videos)

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#36]
After the admin logins in, they can add / modify / delete the videos which will be shown to the users (Fitility app)
- As you can see, when you click on Dance Radio Buttons only those fields should be visible. If the admin wants to add workout videos then additional fields should be visible. 
- Add screenshots to the PR
Refer to this [design](https://www.figma.com/proto/cEXaOK7jOuq1neyWXJAN5g/Untitled?node-id=1%3A2&scaling=scale-down)
If the link is not working, refer to this image:
![add dance videos](https://user-images.githubusercontent.com/55777560/106121651-cc389a80-617d-11eb-8526-ae1ea8d2b73e.PNG)
![add workout videos](https://user-images.githubusercontent.com/55777560/106121659-cd69c780-617d-11eb-8f9b-89a89ef34f1a.PNG)

**Comment by niloysikdar** [comment]
Want to work on this.

**Comment by samflab** [comment]
assigned
