### ISSUE TITLE
Admin Panel : Home Page (Modify)

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#37]
After the admin logins in, they can add / modify / delete the videos which will be shown to the users (Fitility app)
Refer to this [design](https://www.figma.com/proto/cEXaOK7jOuq1neyWXJAN5g/Untitled?node-id=7%3A87&scaling=scale-down)
- In the drop down, the list of videos should be available (from database) and after selecting the video, its respective details should be displayed after which the admin can edit and save the changes.
- Also include the required changes for Dance and Workout Pages
- Add screenshots in the PR.
If the link is not working, refer to this image:
![update](https://user-images.githubusercontent.com/55777560/106130702-b29c5080-6187-11eb-9d05-c3ae0da7cfdc.PNG)

**Comment by niloysikdar** [comment]
Want to work on this.

**Comment by samflab** [comment]
assigned
