### ISSUE TITLE
Admin Panel : Home Page (Delete)

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#38]
Refer to this [design](https://www.figma.com/proto/cEXaOK7jOuq1neyWXJAN5g/Untitled?node-id=7%3A174&scaling=scale-down)
- Almost the same functionality as update [issue](https://github.com/samflab/Fitility-OpenSource/issues/37)
- Add screenshots to the PR.
If the link is not working, refer to the images
![delete](https://user-images.githubusercontent.com/55777560/106131277-81705000-6188-11eb-883f-969bd23f93a0.PNG)

**Comment by niloysikdar** [comment]
Want to work on this .

**Comment by samflab** [comment]
assigned !
