### ISSUE TITLE
Admin Panel : Adding Dance and Workout Videos

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#39]
After filling the form, the required details should be added to the database on Firebase.
The same data should be retrieved and shown to the users of Fitility app

**Comment by niloysikdar** [comment]
Want to work on this.

**Comment by samflab** [comment]
assigned

**Comment by Niloy-Sikdar-001** [comment]
Want to continue with the issue .

**Comment by niloysikdar** [comment]
Want to continue with the issue @samflab  .

**Comment by samflab** [comment]
thanks, go ahead.
