### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#4]
This page should appear as soon as the user logs into the app
Follow this [design](https://xd.adobe.com/view/8ac5be57-dfd4-47f0-a4e9-4ec8285b55cc-df96/screen/88dcfa49-f896-4483-bdc6-373598968c11/) for the page.
- all the required assets are all downloadable. 
- please use proper naming of the assets
- please use modular code for the frontend, avoid writing complex and lengthy code.
if you are the making a PR, please attach a screenshot as well.

**Comment by niloysikdar** [comment]
I want to work on this issue . 
-- Niloy Sikdar , JWOC mentee .

**Comment by samflab** [comment]
assigned you this issue
