### ISSUE TITLE
Admin Panel : Profile Page

### ISSUE THREAD

**Issue by samflab** [samflab/Fitility-OpenSource#42]
Refer to this [design](https://www.figma.com/proto/cEXaOK7jOuq1neyWXJAN5g/Untitled?node-id=7%3A241&scaling=scale-down)
- Add a logout functionality
- Screenshots in the PR
If the link is not working, refer to this image:
![profile](https://user-images.githubusercontent.com/55777560/106132769-60a8fa00-618a-11eb-9b7c-4f53f722777a.PNG)

**Comment by niloysikdar** [comment]
Want to work on this .

**Comment by samflab** [comment]
assigned
